/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilComponent {
    'attributeMessage': string;
  }
  interface StencilComponentAttributes extends StencilHTMLAttributes {
    'attributeMessage'?: string;
    'onElement-dispatch'?: (event: CustomEvent<string>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilComponent': Components.StencilComponent;
  }

  interface StencilIntrinsicElements {
    'stencil-component': Components.StencilComponentAttributes;
  }


  interface HTMLStencilComponentElement extends Components.StencilComponent, HTMLStencilElement {}
  var HTMLStencilComponentElement: {
    prototype: HTMLStencilComponentElement;
    new (): HTMLStencilComponentElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-component': HTMLStencilComponentElement
  }

  interface ElementTagNameMap {
    'stencil-component': HTMLStencilComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
